app/models/event_instance.rb
features/hangout.feature
spec/factories/event_instances.rb
spec/models/event_instance_spec.rb

PT story (addition to previous https://github.com/AgileVentures/WebsiteOne/pull/613 and https://github.com/AgileVentures/WebsiteOne/pull/592) https://www.pivotaltracker.com/story/show/65542324
- Triggers a tweet (TwitterService) with link to recording when `yt_video_id` is present on an EventInstance.
- One version for 'Scrum' and one version for 'PairProgramming' categories

Tweet YT recordings

---

app/controllers/concerns/statistics.rb

- refactored 'calculate_duration' to display duration as integer and as minutes rather than seconds.

Statistics - calculate_duration

---

Gemfile.lock

- Updated therubyracer version, this will bump the version of libv8 up
to make it more compatible with Mac OS X Yosemite

Updated therubyracer version

---

app/assets/javascripts/documents.js
app/views/static_pages/show.html.erb

There was a duplicate script block at the bottom of the static_pages show template. I believe this was causing a conflict between the global defined script performing exacting the same action.
PT => https://www.pivotaltracker.com/story/show/76848756

PATCH: Fix revisions toggle link on about page

---

Gemfile.lock
app/controllers/event_instances_controller.rb
app/models/event_instance.rb
app/views/event_instances/_hangout_button.html.erb
config/settings.yml
config/settings/production.yml
db/migrate/20150520184236_add_hoa_status_to_event_instances.rb
db/schema.rb
features/hangout.feature
features/step_definitions/hangout_steps.rb
spec/controllers/event_instances_controller_spec.rb
spec/factories/event_instances.rb
spec/models/event_instance_spec.rb
spec/support/shared_examples/shared_example_for_hangout_button.rb

* Add column :hoa_status to event_instances table.
* EventInstancesController#update receive hoa_status from
HangoutConnection
* EventInstance model don't update after set hoa_status to finished
* EventInstance#live? respond true if not finished and updated within 2
minutes.
* Remove 'request.scheme' from CallbackURL hangout button field, to make
posible use with either http or https protocol.
* Set Settings.hangout.app_id and Settings.slack.notifications and
Settings.twitter.notifications to ENV variables to prevent calls from
development & staging.

Trace start and end of broadcasting at hangouts.

---

app/controllers/event_instances_controller.rb
spec/controllers/event_instances_controller_spec.rb

* Made a few changes in the list of conditions for sending slack notifications so that only valid urls are posted.
* According to the new rules, a slack notification is posted when:
- A user clicks on the "Notify on slack" button in the hangouts app and the hangout url and youtube video id are present (and not blank).
- When there is a update in the hangout url or youtube video id. This allows for the youtube notification to be posted only when there is a valid youtube id in the database.
PS - Sorry for the sphagetti code but I couldn't think of a way to make these conditionals better without making things more complex. Any design suggestions are welcome.

Bugfix for Invalid youtube video urls in Slack Notification

---

app/views/event_instances/_hangout_button.html.erb
config/settings.yml
spec/support/shared_examples/shared_example_for_hangout_button.rb

Set the ssl site at `ENV['SSL_HOST']` this value must me `websiteone-production.herokuapp.com`
Then send to hangouts the ssl site at `callbackUrl`, with this value if it is set, otherwise with `root_url`.
At this moment, some disqus test are failing. 
This PR alone will not have effect, until the hot fix done at HangoutConnection will be reverted.

Use ssl url for communication with hangouts

---

app/services/slack_service.rb
spec/services/slack_service_spec.rb

* Add a check in the slack service to make sure that blank notifications don't get sent out to agile-bot
Fixes AgileVentures/agile-bot#2

Fix Blank Youtube Notifications

---

CONTRIBUTING.md
docs/how_to_submit_a_pull_request_on_github.md

fixes #799 
This is a CONTRIBUTING.md doc based on the one we have for LocalSupport.  GitHub automatically links this file into the UI for pull requests and many developers will expect to find help and advice on how to contribute in this file:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
This is a proposal based on the approximate workflow I've been following since we switched to waffle, and I'm very interested to hear about how we can word this better, make changes etc. so that we have a workflow that works well for as many of us as possible.

Adds CONTRIBUTING.md

---

Gemfile
Gemfile.lock
lib/tasks/brakeman.rake
lib/tasks/bundle-audit.rake

Resubmission of this PR all fixed up now
This PR adds security auditing tasks but does not put them in the ci build since that would break due to audit failures.
This is because bundler has found a lot of out of date gems with known security vulnerabilities.
Brakeman has found some vulnerabilities too but it does not fail the build (or at least not as configured).
You can see sample output here in the attached files:
[bundler.txt](https://github.com/AgileVentures/WebsiteOne/files/141602/bundler.txt)
[brakeman.txt](https://github.com/AgileVentures/WebsiteOne/files/141603/brakeman.txt)
If you don't want to add it to the default rake task but still want to be able to run "on demand" then just remove the final line in both of the new .rake files and you can run
```
bundle exec rake …
```

brakeman and bundler added

---

Gemfile
Gemfile.lock
app/models/user.rb
features/users/create_users.feature

Customize error message when GitHub and G+ signup fail due to no public email

---

app/helpers/event_instances_helper.rb
spec/helpers/event_instances_helper_spec.rb

* remove time to EventInstance id, it will be set at Hangout app
* update test of helper generate_event_instance_id

Removes time from hangout_id sent to HangoutConnection (#1015)

---

app/views/events/index.html.erb
features/events/list_repeating_events.feature
features/step_definitions/event_steps.rb

fixes #953
We've been trying to test this, but it relies on being able to set the timezone for the capybara javascript driver, which we can't yet work out how to do - have opened a ticket with capybara: https://github.com/jnicklas/capybara/issues/1685

Test driven fix of the timezone issue on the events list page

---

app/assets/javascripts/select_time_zone_and_update_date_and_time.js
app/controllers/events_controller.rb
app/views/events/_form.html.erb
features/events/create_events.feature
features/events/edit_future_event.feature
features/events/edit_past_event.feature
features/step_definitions/event_steps.rb
spec/javascripts/select_time_zone_and_update_date_and_time_spec.js

* adds next time to event form as hidden field and uses in javascript, but introduces time progression bug
* adjusts event controller to take account of next event date when working out timezone during event save
* fixes the jasmine test for the timezone selector by adjusting the date
* adjusts timezone selector to use start date when updating start date
* adds acceptance tests of timezone edits
* extracting method for code climate
* quick fix to silly variable mistake

Allow user to create event in local timezone (#1079)

---

app/assets/javascripts/select_time_zone_and_update_date_and_time.js
app/controllers/events_controller.rb
app/views/events/_form.html.erb
features/events/create_events.feature
features/events/edit_future_event.feature
features/events/edit_past_event.feature
features/step_definitions/event_steps.rb
spec/javascripts/select_time_zone_and_update_date_and_time_spec.js

* adds next time to event form as hidden field and uses in javascript, but introduces time progression bug
* adjusts event controller to take account of next event date when working out timezone during event save
* fixes the jasmine test for the timezone selector by adjusting the date
* adjusts timezone selector to use start date when updating start date
* adds acceptance tests of timezone edits
* extracting method for code climate
* quick fix to silly variable mistake

Allow user to create event in local timezone (#1079) (#1081)

---

app/models/user.rb
config/locales/en.yml
features/step_definitions/user_steps.rb
features/users/create_users.feature

Provides link to GitHub page (instructions to sign up) in public email error message

1064 - instructions to signup with github public email

---

app/controllers/authentications_controller.rb
spec/controllers/authentications_controller_spec.rb
spec/requests/authentications_spec.rb

Adds more feedback in error message. 
This separates out the message change for issue #1230 and should be merged first before #1130 which focuses on resolving github unlinking.

error message for failed github unlinking

---

app.json

Configure heroku app.json to use Free dyno tier for review app
Addresses: https://github.com/AgileVentures/WebsiteOne/issues/1271

1271 Use free tier dyno for review app

---

app/views/charges/edit.html.erb
app/views/charges/premium.html.erb

Addresses: https://github.com/AgileVentures/WebsiteOne/issues/1267
I changed locale setting of stripe from **auto** to **en-US**. So developers can work on project without need of tweaking cassette files and also to prevent displaying the popup in different languages for users.

1267 Edit stripe locale config

---

app/views/users/profile/_summary.html.erb
features/users/profile_privacy.feature

Fixes #1324 
This change removes the "Hire me" button from the logged in user's profile page.  The button is still visible to anyone except for the current user.
Removed ```@javascript``` from the cucumber tests related to this change.  With it in there, the ```sign out``` step fails with the error:  
```
undefined method `submit' for #<Capybara::Poltergeist::Driver:0x007f8f12ec4110> (NoMethodError)
./features/step_definitions/user_steps.rb:49:in `/^I sign out$/'
features/users/profile_privacy.feature:102:in `And I sign out'
```
This is my first pull request on the project.  Any feedback or changes needed are welcome :)

1324 hire me button removed for the logged in user 

---

Gemfile
Gemfile.lock
app/views/events/show.html.erb
spec/views/events/show.html.erb_spec.rb

Adds the autolink gem, and uses it on the Event#show page re this issue: Fixes https://github.com/AgileVentures/WebsiteOne/issues/769

Autolink urls in event descriptions on event show page

---

CONTRIBUTING.md

I fixed two links in CONTRIBUTING.md
When clicking this hyperlink:
We are currently redirected to: https://github.com/AgileVentures/WebsiteOne/pulls
When clicking this hyperlink:
We currently get a 404.
I have replaced both links with more appropriate redirections.
No new tests have been added. All current tests pass

1577-fixing-broken-links-in-contributing

---

app/views/subscriptions/new.html.erb

Included AV logo in our stripe popups
[https://github.com/AgileVentures/WebsiteOne/issues/1253](url)
Included the AV Logo in strip popup by including (data-image="") in new.html
By Including the AV Logo in Stripe popup, User can know that they are paying to Agile Ventures through stripe.
Tested in Chrome
Chrome Version 56.0.2924.87

1253_add_images_logos_stripe

---

app/presenters/event_instance_presenter.rb
features/hangouts/hangout.feature
spec/presenters/event_instance_presenter_spec.rb
spec/views/event_instances/index.html.erb_spec.rb
spec/views/projects/show.html.erb_spec.rb
spec/views/users/show.html.erb_spec.rb

fixes #1655 
Tested manually by comparing /projects/websiteone#video on live site to local.

Fix video link from http to https

---

app/views/layouts/_footer.html.erb
features/basic_layout.feature
spec/views/layouts/application.html.erb_spec.rb

closes #1738 
Added a press-kit link to the footer. Also added a rspec test to `application.html.erb_spec.rb` in
```ruby
context 'within the site footer' do
...
end
```
to test there is a such link called "Press Kit"

Add Press-Kit link to footer

---

app/models/event.rb
features/hangouts/edit_hangout_url.feature

switch to recent hangout checks on created_at so we do not get confused by later manual updates to the youtube url

---

app/jobs/slack_invite_job.rb
spec/jobs/slack_invite_job_spec.rb

add dependency injection of token and be robust to nil token and non-string elements in failure email

---

app/services/slack_service.rb
spec/services/slack_service_spec.rb

fixes #1943
So here I've added the ability to ping multiple slack channels - and added a test to ensure that works for pair programming.
I've updated the channels so that the marketing meeting will ping the marketing channel and av_community channel and that the autograders meeting will also ping the betasaasers channel ...
I've also merged in the minor refactoring of using mock_model, but I'm worried that this is all getting a bit messy, and we need to maybe re-design pushing from TDD.  
I guess the key thing I want to move towards is supporting private events that would ping premium_extra - that's a bigger undertaking ...
also, the specs are rather difficult to follow, and maybe driving from Cucumber would make this all more comprehensible ...

support posting links to multiple channels

---

app/views/layouts/_head.html.erb
features/pages.feature
features/step_definitions/basic_steps.rb
features/step_definitions/pages_steps.rb

Two acceptance tests were added to the cucumber features set to ensure that the page title displayed to users when they visit the AgileVentures site reflected the page they were viewing or displayed the default 'AgileVentures'.  The view partial, _head.html.erb, was amended to remove the 'WebsiteOne' text.
Currently when a user visits the AgileVentures site, the browser tab will display a page title which includes the text 'WebsiteOne'. This is not meant to be seen by users, and refers to the name of the project used by the development team.
Created two cucumber scenarios, one that checks that the title includes the page that the user is on in the browser tab, e.g. if a user is on the 'Home' page, then the browser tab should display 'Home | AgileVentures". A second scenario checks for …

fixes #2017 - WebsiteOne appears in the pages title

---

app/models/user.rb
spec/models/user_spec.rb

Handle `nil` when `Settings.privileged_users` doesn't exists.
Fixes https://github.com/AgileVentures/WebsiteOne/issues/2209

Handle nil on Settings.privileged_users

---

Gemfile
Gemfile.lock

Upgrade to ruby version 2.5.0 for having the [performance improvements](https://www.ruby-lang.org/en/downloads/) that come with the upgrade.

Upgrade ruby to latest version.

---

app/services/karma_calculator.rb
lib/tasks/scheduler.rake
spec/services/karma_calculator_spec.rb

The database was being queried to grab all EventInstances for each user. The EventInstance query is the same for each user. So that is about 8000 repetitive queries to the database. Moved this query outside of the loop.
Reoccurring Airbrake issues related to the KarmaCalculator show that an exception is occurring and the process is killed. Issue #2004 in particular due to a bad PG connection and time out.
According to the Heroku website "Scheduled jobs are meant to execute short running tasks or enqueue longer running tasks into a background job queue. Anything that takes longer than a couple of minutes to complete should use a worker dyno to run.” Confirmed this is not being ran on a worker dyno.
Fixes #2221 
I tested the speed of this rake task on my system and it revealed that it would …

Query database once for all users

---

app/controllers/events_controller.rb
app/helpers/event_helper.rb
app/models/event.rb
app/views/events/show.html.erb
db/migrate/20180507045056_add_column_modifier_id_to_events.rb
db/schema.rb
features/events/show_event.feature
features/step_definitions/event_steps.rb
spec/helpers/event_helper_spec.rb
spec/models/event_spec.rb

Displays details for both the creator and modifier of an event on the show page.
Fixes #2301
Currently when someone modifies an event the creator info is destroyed.
This is needed so that we can preserve the creator info and show who
modified the event.
Added cucumber tests for the event show page to check that both creator
and modifier info exists on the page after an event is edited. Added unit tests where applicable.
See issue #2301 for screenshots

Show creator and modifier info on event show page

---

spec/javascripts/flash_spec.js

The fail was caused by this expectation expect(timeoutSpy.calls.mostRecent().args[1]).toEqual(5000) where mostRecent().args will sometimes return only one argument instead of two hence .arg[1] gives undefined.
Fixes #2340

Fix intermittent fail in jasmine tests

---

config/cucumber.yml

When tests fail on CI there showing as passing. We used to run a
second_try, but that was removed for some reason. Setting first_try to
fail so that failing tests are shown as failing.
Created this change to see if it affects CI reporting of failing tests.

Set tests to fail on first_try

---

db/schema.rb

PG stats are enabled on Heroku postgres databases by default. Enabling
PG stats uses up more memory and are not needed on local dev machine
since PG stats are used to collect production statistical data that can
used for optimization plans.

Remove pg stats

---

app/services/slack_service.rb
spec/services/slack_service_spec.rb

add phoenix slack channel id to project lookup and prevent posts to nil channels

---

app/views/events/show.html.erb
features/step_definitions/event_instances_steps.rb

Using %e format directive was adding an extra space in the rspec test
matchers.
Here is more information:
https://stackoverflow.com/questions/20129049/random-space-in-rails-datetime-when-using-rspec
And the link to the format directives:
https://apidock.com/ruby/DateTime/strftime
This is to fix tests that were passing at the end of last month when there were two digit days and now that we're on single digit days the use of %e is in the rspec matcher is adding an extra space. 
Need to use %-d instead.
Fixes #2415

Remove extra space by using %-d format directive

---

Gemfile.lock
config/initializers/timeout.rb
docs/project_setup.md

Relates to issue: https://github.com/AgileVentures/WebsiteOne/issues/2419

Update specific gems

---

app/controllers/projects_controller.rb
app/views/projects/_connections.html.erb
app/views/projects/_form.html.erb
db/migrate/20180729040001_add_slack_channel_name_to_projects.rb
db/schema.rb
features/projects/connections.feature
features/projects/create_projects.feature
features/projects/edit_project.feature
features/step_definitions/projects_steps.rb

Added a link so that users can navigate to the projects slack channel
This is so that individuals can easily navigate to a projects slack channel.
Fixes #770 
Added tests to ensure link is present.

Add Slack channel link to the projects show page

---

Gemfile
Gemfile.lock

`acts_as_follower` gem is no longer maintained. Forked Gem to fix deprecation
warning spamming the output of our tests.
Deprecation warning for use of custom classes is spamming the output of tests. Applied patch. See https://github.com/AgileVentures/acts_as_follower/pull/1 for more info.
Tests passing with zero instances of a deprecation warning printing, it will still print to the output if a custom class is actually used.
Fixes #2499

Use AgileVentures forked Gem

---

config/database.yml

Pointing to host db prevents local developers from running server and visiting site

Remove db host from database.yml

---

app/controllers/event_instances_controller.rb
app/services/slack_service.rb

Refactored Event Instance update method and the Slack Services post method, and added error handling for any events that may occur when communicating with external services.
Fixes #2452 
This is mainly in response to recent issues that caused end users to see a 500 error message without any explanation of what happened. The main culprit was an invalid API token, which has now been updated. 
Screen shot for when an error occurs.

Add error handling to Slack/Gitter API calls

---

app/views/projects/_listing.html.erb
features/projects/deactive_owners.feature
features/projects/list_projects.feature
features/step_definitions/projects_steps.rb

Display anonymous for deactive project owners
Added conditional to display anonymous when project owner has
deactivated their AV account instead of linking to the project owner's
show page.
This fixes the undefined method error caught by Airbrake and fixes the
500 error users are seeing when visiting a project index page when a
project on that page is assigned to a deactivated account.
This fixes #2574 
As of today if you visit page [https://www.agileventures.org/projects?page=22](https://www.agileventures.org/projects?page=22) you will see a 500 error. 
This is being caused by a project on that page has a project owner who has deactivated their account.
Feature test added.
prior to implementing fix the test result showed the following:
```
When I visit "/projects" …
```

Fix project index page not displaying

---

app/models/event_instance.rb
features/events/show_event.feature
features/step_definitions/event_steps.rb

When an event exists before the actual event start date the event occurrence method is returning nil.
This is happening when a user creates an event and starts a hangout, but then after the hangout finishes the event is edited (most likely no one showed and so they reschedule) to start at a later date. 
Fixes #2603, Fixes #2233, and Fixes #2043
This is to address airbrake issue for an undefined method on nil class error
Added spec to catch the undefined method :- for nil object.
The event show page will issue a 500 internal error due to an event
instance existing before the actual event start date.

Fix undefined method for nil class when viewing event show page

---

config/initializers/paper_trail.rb

Removed associations tracking config setting, because it is now the
default setting due to the associations tracking utility is now a
seperate gem.
Fixes #2623 
To clean up test output.
All tests passing locally

Remove default PaperTrail config

---

app/models/null_user.rb
app/views/projects/_listing.html.erb
db/seeds.rb
features/projects/deactive_owners.feature
features/step_definitions/projects_steps.rb
features/step_definitions/user_steps.rb
lib/tasks/create_anonymous_user.rake

Updated the null user class to have an id.
This allows removal of the conditional in the view, because the
<link_to> method can now render since the returned NullUser object has
an id.
We should create an anonymous/ghost user in production with an id of -1.
(See https://github.com/AgileVentures/WebsiteOne/pull/2588#discussion_r223558623 for why the id of -1 is being used rather than a positive id # that's currently not being used in production)
Fixes #2583
This addition allows removal of code in the view.
tests already in place.

Update null user to have an id

---

app/assets/stylesheets/application.scss

Fixes #2682 spacing between embedded video and video links. 
Add margin below embedded video to add spacing between video and links
This change is required to fix spacing issue on profile page.
https://github.com/AgileVentures/WebsiteOne/issues/2682

Better spacing between embedded video and video links

---

features/users/sign_in.feature

This test is failing regularly and causing the need to rerun the build several times.
This will tell CI to skip it

Add intermittent failing test tag

---

Gemfile
Gemfile.lock

fixes #2686
Removed rack-timeout from development env - now it's possible to use pry and byebug
In my opinion we should not use it in development anyway. From rack-timeout documentation:
> Rack::Timeout is not a solution to the problem of long-running requests, it's a debug and remediation tool. App developers should track rack-timeout's data and address recurring instances of particular timeouts, for example by refactoring code so it runs faster or offsetting lengthy work to happen asynchronously.
Also added rdoc gem to Gemfile, Without this I could not install this app locally on linux manjaro due to missing `rdoc/markdown/to_html` file.

Removed rack-timeout from development env, fixes 2686

---

app/controllers/users_controller.rb
features/step_definitions/event_steps.rb
features/users/user_list.feature

fixes #1811 
Make project dropdown only show active projects on volunteers page
Filter only active projects to be displayed on the projects dropdown
To reduce the number of projects displaved on the dropdown
I havent writen acceptance tests yet, but I have tested manually on the UI
Fixes #1811

Make event drop down show only active projects

---

lib/validators/image_url_validator.rb
spec/models/project_spec.rb

The messages hash has a value listing all errors in an array. Updated
Image validator to append error messages to the array instead of over
writing the array with a String. This is being done because it causes
Rails ActiveRecord to error out when it does post validation checks,
because it's expecting an array, but instead receives a String.
Fixes #2857

Append error message to array

---

app/models/event.rb
app/models/event_instance.rb
app/models/slack_channel.rb
app/services/hangout_notification_service.rb
app/services/youtube_notification_service.rb
db/migrate/20190412143519_create_join_table_events_slack_channel.rb
lib/channels_list.rb
spec/models/event_spec.rb
spec/services/hangout_notification_service_spec.rb
spec/services/youtube_notification_service_spec.rb

- Add associations
- Add join table migration
- Add models test
- refactor notification services tests
Co-authored-by: Gideon Kimutai <gideon.kimutai.kim@gmail.com>
fixes #3135 
Not really happy with the youtubenotificationservice spec... 
the easiest thing to show proof of concept was to add it to an existing test entitled `sends the correct slack message to the correct channels`, but this does not help for others to understand what we are testing
also, I worry about having three expectations in the same it block... 
@tansaku please have a look and see what you think
we talked about a rake task to add event.slack_channels, but it's a bit different... I could come up with a hardcoded list of recurring events, which are not pinging the channels we expect?

Add event slack channels

---

app/assets/javascripts/event_datepicker.js
spec/javascripts/event_datepicker_spec.js

Fix UI bug when repeat end is set to never on the UI
[Fixes #3215](https://github.com/AgileVentures/WebsiteOne/issues/3215)
N/A

Persist empty string when repeat end is set to never

---

app/controllers/event_instances_controller.rb
spec/controllers/event_instances_controller_spec.rb

These methods were causing code climate issues, and they're actually no longer needed as we're not receiving telemetry data from google anymore. 
Fixes #3226

Remove obsolete methods

---

app/controllers/projects_controller.rb
config/routes.rb
spec/controllers/projects_controller_spec.rb

This pull request removes destroy action from projects controller since it is not been used.
- Delete commented test
-  exempt destroy routes
fixes #[2968](https://github.com/AgileVentures/WebsiteOne/issues/2968)
N/A
N/A

Remove destroy action from Project Controller

---

app/models/project.rb

Removes the `Dangerous query method` DEPRECATION warning when running cucumber tests. 
fixes #2924

Wrapped LOWER sql call with Arel.sql

---

.codeclimate.yml

Updated to [version 2](https://docs.codeclimate.com/docs/advanced-configuration#section-analysis-configuration-versions) used in Codeclimate, which allows tunable duplicate code checks.
WIP b/c I'm not sure how to test this w/o an open source project and need to tune the exact values of various `threshold` constants.
fixes #2976

Set Codeclimate duplicate and similar code threshold to 3

---

CONTRIBUTING.md

We are now using Zenhub for issue tracking. Update Contribution guidelines to reflect the same.
Fixes #3407

Update from Waffle to Zenhub

---

.semaphore/semaphore.yml

Added yml file to configure v2 of semaphore. 
Currently all jobs run sequentially as it was mostly copied from our v1 setup. It is possible to configure parallel jobs which could decrease our ci time.
Once this is merged then we can disconnect v1 and rebase current PRs.
If anyone is interested in parallelizing these jobs. Here is a good place to start: https://docs.semaphoreci.com/guided-tour/customizing-your-pipeline/#defining-blocks-with-parallel-jobs

Setup semaphore v2

---

.rubocop.yml
.semaphore/semaphore.yml
Dockerfile
Gemfile
Gemfile.lock
docs/c9/install_notes.md
docs/ubuntu/ubuntu_14.04_manual_install_notes.md

Updating Ruby to 2.6.3 so that we can upgrade to a newer Heroku stack. 
This is in preparation of updating to 2.7.2 - see PR #3640

Update Ruby version to 2.6.3
