- app/controllers/users_controller.rb
- features/users/user_list.feature
- spec/controllers/users_controller_spec.rb
https://www.pivotaltracker.com/n/projects/982890/stories/78088460
fix `PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "C"` error and tests for that method what was caused
> Advanced user search2

- app/presenters/users/user_presenter.rb
- app/views/users/profile/_summary.html.erb
- spec/presenters/users/user_presenter_spec.rb
- spec/views/users/show.html.erb_spec.rb
https://www.pivotaltracker.com/n/projects/982890/stories/78649838
I added this option next to the user timezone that we can see the user timezone differences from UTC
> Add UTC+n or UTC-n to the user profile page.

- app/models/event_instance.rb
- had to add method to validate yt recording to EventInstance since ppl are not recording their sessions and we don't want to push out tweets with links that don't lead anywhere.
> Validate YT recording

- app/helpers/projects_helper.rb
- spec/helpers/projects_helper_spec.rb
Pivotal Tracker: https://www.pivotaltracker.com/story/show/82977864
- Refactor existing `projects_helper_spec` to use new rspec expect syntax
- Refactor `app/helpers/projects_helper.rb` implementation
> Projects helper specs

- app/views/dashboard/index.html.erb
https://www.pivotaltracker.com/story/show/80032336
> Fix #undefined url that append when clicked Dashboard tabs

- app/assets/stylesheets/layout/navbar.css.scss
https://www.pivotaltracker.com/n/projects/982890/stories/76848756
> 35px avatar on navbar

- app/views/articles/_article.html.erb
- app/views/articles/index.html.erb
- app/views/documents/show.html.erb
- app/views/projects/index.html.erb
- app/views/static_pages/show.html.erb
- spec/views/documents/show.html.erb_spec.rb
Fixed test on rspec.
https://www.pivotaltracker.com/n/projects/982890/stories/76848756
> Iconsbuttonslarger

- app/views/dashboard/index.html.erb
Use the right color range on map (dashboard). See the AV profile repo on GitHub for colors.
https://www.pivotaltracker.com/n/projects/982890/stories/76848756
> Changed to darker color of dashboard map

- app/assets/javascripts/search_toggle.js
- app/assets/stylesheets/layout/navbar.css.scss
- app/views/layouts/_navbar.html.erb
- features/step_definitions/advanced_site_search.rb
- Vertical align the Google custom search image in input field
- Fix issue where user menu was partly hidden after closing the search form
- Minor refactor of `navbar.css.scss`
> Patch: Google custom search

- .gitignore
- app/models/status.rb
- db/migrate/20150410173625_add_status_count_to_users.rb
- db/schema.rb
- spec/models/status_spec.rb
- spec/models/user_spec.rb
- spec/presenters/users/user_presenter_spec.rb
- spec/views/users/index.html.erb_spec.rb
Add counter cache to User for status association.
> User counter cache

- app/views/articles/_article.html.erb
- app/views/events/show.html.erb
"Live Soon" button on events show page should NOT be a button. Bad HCI
https://www.pivotaltracker.com/n/projects/982890/stories/76848756
> Livebutton

- app/assets/javascripts/users.js
- app/models/user.rb
- app/presenters/users/user_presenter.rb
- app/views/layouts/_require_users_profile.html.erb
- app/views/layouts/application.html.erb
- app/views/visitors/index.html.erb
- features/remind_complete_profile.feature
- features/step_definitions/basic_steps.rb
- features/step_definitions/user_steps.rb
- features/support/helpers.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/presenters/users/user_presenter_spec.rb
Remind user to complete profile, https://www.pivotaltracker.com/story/show/78354128
> Remind complete profile

- app/views/event_instances/_hangout_button.html.erb
- app/views/projects/show.html.erb
- features/projects.feature
I modified views/project/show and partial that render hangout button.
New hangout button for users that no follow project works great but many cucumber tests are now failing.
In my opinion these failing test are no related to project/show view.
So Thomas if you have a moment please take a look on this.
https://www.pivotaltracker.com/story/show/76848756
> add a comment that you need to join the project to see the hangout button

- app/assets/javascripts/event_instances.js
- app/presenters/event_instance_presenter.rb
- spec/presenters/hangout_presenter_spec.rb
Fix and Regresion test when person is nil at event_instance.participants
Fix accordion behaviour on second page
> Infinite scroll

- Gemfile.lock
- app/controllers/event_instances_controller.rb
- app/models/event_instance.rb
- app/views/event_instances/_hangout_button.html.erb
- config/settings.yml
- config/settings/production.yml
- db/migrate/20150520184236_add_hoa_status_to_event_instances.rb
- db/schema.rb
- features/hangout.feature
- features/step_definitions/hangout_steps.rb
- spec/controllers/event_instances_controller_spec.rb
- spec/models/event_instance_spec.rb
- spec/support/shared_examples/shared_example_for_hangout_button.rb
Reverts AgileVentures/WebsiteOne#694
> Revert "Hangout"

- app/controllers/scrums_controller.rb
- spec/controllers/scrums_controller_spec.rb
- fix for sorting of response in scrums_controller
> PATCH for sorting response 

- app/views/events/_form.html.erb
- features/disqus.feature
- spec/controllers/events_controller_spec.rb
* changed default setting of event category 
* refactored event_controller_spec to 3.x syntax
> Events Form fix

- app/controllers/event_instances_controller.rb
- app/services/slack_service.rb
- spec/controllers/event_instances_controller_spec.rb
- spec/services/slack_service_spec.rb
* Pivotal Story: https://www.pivotaltracker.com/story/show/105918590
* The Slack Hangout Notification now includes the youtube video link for the hangout.
> Feature: Post Hangout Video Link to Slack

- app/assets/stylesheets/global/projects.css.scss
- app/views/projects/_connections.html.erb
- app/views/projects/_highlight_box.html.erb
- app/views/projects/_members_list.html.erb
this is a replacement for PR #713 - the original PR #713 may be closed as the OP seems unresponsive
this is the same commit as the head of PR #713 (0723a63477) but rebased onto the current develop branch
this PR may close this story --> https://www.pivotaltracker.com/story/show/85684660
> draw borders around project sidebar groups

- Gemfile
- config/initializers/airbrake.rb
Initialize `airbrake` in production only
> load airbrake in production only

- app/helpers/event_helper.rb
- app/views/events/index.html.erb
- config/application.rb
- config/database.yml
- features/events.feature
- spec/helpers/event_helper_spec.rb
- spec/views/events/index.html.erb_spec.rb
Everything is working for showing local time.   Had to adjust a few tests to adapt to the more normal time display format.
This work closes #753
> 82968236 show local time

- Gemfile
- Gemfile.lock
> update gemfile to use atleast local_time 1.0.3

- features/support/env.rb
* Fixes problem with failing cucumber steps that involve HOA button (works locally at my machine)
* Build upon @mtc2013 's old PR #710 
* Fixes #751, fixes #777
> fix for failing hoa_button in test env

- Gemfile
- Gemfile.lock
- features/support/env.rb
hmm CI not running on this kind of pull request ... ah it is now ...
> Trying to increase cucumber javascript test robustness

- features/support/env.rb
> specifies phantomjs path as per phantomjs gem

- spec/migrations/event_time_refactor_spec.rb
> supresses migration output

- features/projects.feature
- features/step_definitions/basic_steps.rb
- lib/validators/pivotal_tracker_url_validator.rb
- spec/lib/validators/pivotal_tracker_url_validator_spec.rb
- spec/models/project_spec.rb
> Adds support for new pivotal tracker link format

- app/views/devise/registrations/new.html.erb
- config/settings.yml
- config/settings/test.yml
> Improving email registration disabled message

- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- features/step_definitions/basic_steps.rb
- features/users/create_users.feature
> Fix bugs with icons and error messages

- CONTRIBUTING.md
- docs/development_environment_set_up.md
- docs/how_to_submit_a_pull_request_on_github.md
- docs/osx/el_capitan_10.11.2_install_notes.md
- docs/project_setup.md
fixes #863
When this gets merged we should ensure that the relevant pages get deleted in the:
> Consolidates getting started documentation

- app/assets/javascripts/global-modules/hangout_button.js
- spec/javascripts/hangout_button_spec.js
> increases hoa widget size so that we have text of "Start Hangout on Air"

- app/assets/javascripts/application.js
- app/assets/javascripts/events.js
- app/views/events/index.html.erb
- features/events.feature
- features/step_definitions/event_steps.rb
- spec/javascripts/events_spec.js
> Make event list box clickable

- app/models/user.rb
- features/step_definitions/basic_steps.rb
- features/users/create_users.feature
> removes password error from oauth email missing failure

- Gemfile.lock
- features/documents.feature
- features/step_definitions/articles_steps.rb
- features/step_definitions/basic_steps.rb
- features/step_definitions/documents_steps.rb
- features/step_definitions/layout_steps.rb
- features/support/env.rb
- features/support/helpers.rb
> 750 junk in cucumber log

- app/assets/stylesheets/layout/buttons.scss
- app/views/layouts/_sponsors.html.erb
- changelog.md
> 900 Fix Sponsor/Supporter alignment

- app.json
> add postdeploy script

- docs/README.md
- docs/expanded_mission_statement.md
- docs/mission_statement.md
fixes #867 
When this gets merged we should ensure that the relevant pages get deleted in the:
> Consolidates mission statement

- app/models/event.rb
- features/events/create_events.feature
- features/events/events.feature
- features/step_definitions/basic_steps.rb
- features/step_definitions/event_steps.rb
- spec/controllers/events_controller_spec.rb
> Appropriate defaults for creating events

- app/assets/javascripts/event_datepicker.js
- app/views/events/_form.html.erb
- features/events/create_events.feature
- features/step_definitions/event_steps.rb
- spec/javascripts/event_datepicker_spec.js
> Rename End Time in UTC to End Date and hide appropriately

- app/controllers/events_controller.rb
- spec/requests/events_spec.rb
> Allow pre-filling of new event form with name and category

- config/initializers/slack.rb
- config/settings.yml
- config/settings/test.yml
> Remove agilebot url hardcoding

- app/controllers/events_controller.rb
- app/models/event.rb
- app/services/event_creator_service.rb
- app/views/events/_form.html.erb
- features/events/create_events.feature
- features/events/edit_events.feature
- features/step_definitions/event_steps.rb
> fixes repeat ends not being maintained through edits

- spec/services/slack_service_spec.rb
fixes #919 
looks like most of his got merged in already, but we lost a refactoring
> dries out slack service spec a little

- app/views/events/show.html.erb
- features/events/events.feature
> Fixes event show date bug

- app/assets/stylesheets/application.scss
> adds timeline import back into application.scss

- app/services/slack_service.rb
- spec/services/slack_service_spec.rb
> makes slack service youtube notification include project slug

- app/views/events/_form.html.erb
> Fixes styling on the event form project selector

- app/controllers/events_controller.rb
- config/routes.rb
- features/events/list_events.feature
- features/events/show_event.feature
- features/step_definitions/event_steps.rb
> Creates nested route to show events by project

- app/views/events/_form.html.erb
- features/events/create_events.feature
> Sorts projects alphabetically in event form

- Gemfile
- Gemfile.lock
- config/initializers/stripe.rb
> adds dotenv and gives stripe env vars better names

- app/assets/stylesheets/global/custom.scss
- app/assets/stylesheets/global/docs.scss
- app/assets/stylesheets/global/sidebar.scss
- app/assets/stylesheets/global/users.scss
- app/assets/stylesheets/layout/landing-page.scss
- app/assets/stylesheets/layout/navbar.scss
- app/views/layouts/_navbar.html.erb
- app/views/layouts/_round_banners.html.erb
- app/views/layouts/articles_layout.html.erb
- app/views/layouts/with_sidebar.html.erb
- app/views/layouts/with_sidebar_sponsor_right.html.erb
- app/views/projects/show.html.erb
- app/views/users/index.html.erb
- changelog.md
- features/step_definitions/user_steps.rb
Closes #849
Deployed work in progress here: https://freeranger-wso-mobile.herokuapp.com
> 849 - Too much whitespace around titles and menu on mobile devices

- app/assets/javascripts/users.js
- app/assets/stylesheets/global/users.scss
- app/views/users/_user_list.html.erb
- changelog.md
- features/remind_complete_profile.feature
- features/step_definitions/user_steps.rb
> 744 - Displaying long nicknames

- features/support/fixtures/cassettes/Create_and_maintain_projects/Editing_Pitch_content_with_Mercury_Editor.yml
- features/support/fixtures/cassettes/Events/Create_a_new_event.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_079cf25c43432922de7e4740ede1e0bc81291d95.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_13d29ba326b2f66d36dc8eafac532ec5b03db624.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_5c126d70b5abbd744b4bcae8194613a5d7f24445.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_5cd7ca95f2082562765206d855c386df7cfb3e85.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_c325ece504da49026ce1b1e90f6e3bd7b191c391.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_fd9bf2c7ecb21ae3b1f2dcd97ba1b39dbf0f1e79.yml
- features/support/puffing_billy.rb
> adds some more network noise to the cache and gstatic to the puffing billy config

- README.md
- docs/project_setup.md
> updates setup doc to mention .env file and links README direct to new docs bypassing wiki

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- features/events/create_events.feature
- features/events/list_events.feature
- features/step_definitions/event_steps.rb
- features/support/fixtures/cassettes/Display_Public_Activity/Render_activity.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_b14c8a2bc5b4dffaafd5a198beb1f3fa7b5a6e7b.yml
- features/support/puffing_billy.rb
> 989 filter events by project ui

- features/documents.feature
> adds tags to avoid running intermittently failing js scenarios on CI

- app/views/layouts/_navbar.html.erb
> hides user accounts urls from navbar

- app/assets/stylesheets/global/sponsors.scss
> fix Become a supporter button alignment

- docs/ubuntu/ubuntu_14.04_manual_install_notes.md
fixes #974 
- Manual instruction for ubuntu 14.04 
- Tested against fresh provisioned ubuntu 14.04 in aws.
> 974 websiteone setup problems

- app/helpers/event_helper.rb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- features/events/show_event.feature
- spec/helpers/event_helper_spec.rb
> fix to the event show page timezone and adds helper

- features/step_definitions/activity_feed_steps.rb
- features/step_definitions/basic_steps.rb
- features/step_definitions/documents_steps.rb
- features/step_definitions/email_steps.rb
- features/step_definitions/event_steps.rb
- features/step_definitions/hangout_steps.rb
- features/step_definitions/layout_steps.rb
- features/step_definitions/mercury_steps.rb
- features/step_definitions/newsletter_steps.rb
- features/step_definitions/pages_steps.rb
- features/step_definitions/projects_steps.rb
- features/step_definitions/scrums_steps.rb
- features/step_definitions/user_steps.rb
- features/step_definitions/youtube_steps.rb
Removed unused cucumber step definitions.
Fixes #865
> 865 redundant cucumber step definitions

- Gemfile
- Gemfile.lock
- features/step_definitions/scrums_steps.rb
- features/support/fixtures/cassettes/As_a_site_user/Selecting_videos_from_the_list.yml
- features/support/fixtures/req_cache/get_www.youtube.com_11647e8b2f37481373ca87a6c2a846132ed24242.yml
- features/support/fixtures/req_cache/get_www.youtube.com_51f82ed491cb44ec7a513ab0e54a06ca9ea945e8.yml
Updates the Ruby version from `2.2.2` to `2.3.0`
> Bump ruby version

- app/assets/stylesheets/layout/buttons.scss
> fixes button width

- config/environments/production.rb
- config/initializers/airbrake.rb
> 1026 update airbrake config

- app/models/user.rb
- spec/models/user_spec.rb
> User sign up problem

- app/controllers/events_controller.rb
- features/events/edit_events.feature
- spec/controllers/events_controller_spec.rb
> event update redirection to show page

- app/views/charges/create.html.erb
- app/views/charges/new.html.erb
- features/charge_activity.feature
- features/step_definitions/charge_steps.rb
> changes currency to GBP

- features/sidebar.feature
- features/step_definitions/basic_steps.rb
> makes step do what was originally indented?  and updates feature to correspond to current functionality

- docs/c9/install_notes.md
> c9 install docs

- app/assets/javascripts/select_time_zone_and_update_date_and_time.js
- app/controllers/events_controller.rb
- app/views/events/_form.html.erb
- features/events/create_events.feature
- features/events/edit_future_event.feature
- features/events/edit_past_event.feature
- features/step_definitions/event_steps.rb
- spec/javascripts/select_time_zone_and_update_date_and_time_spec.js
> Allow user to create event in local timezone

- docs/c9/install_notes.md
Removed step to comment timeout as code in new develop branch has been changed.
> Update c9 install_notes.md

- app/views/devise/registrations/new.html.erb
- features/users/create_users.feature
- spec/views/devise/registrations/new.html.erb_spec.rb
@diraulo please review.
fixes #1095
> Disable G+ signups while it doesn't work by hiding

- app/controllers/charges_controller.rb
- app/views/charges/create.html.erb
- app/views/charges/new.html.erb
- app/views/charges/premium.html.erb
- app/views/charges/premiumplus.html.erb
- features/charge_activity.feature
- features/step_definitions/charge_steps.rb
- features/support/fixtures/cassettes/Charge_Users_Money/Sign_up_for_premium_plus_membership.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_ebd9a6004e663bc2f9f4647f6f77e7960eb56201.yml
> adds support for premium plus

- app/controllers/charges_controller.rb
- app/views/charges/create.html.erb
- app/views/charges/premium.html.erb
- app/views/charges/premiumplus.html.erb
- features/charge_activity.feature
- features/step_definitions/charge_steps.rb
- features/support/fixtures/cassettes/Charge_Users_Money/Sign_up_for_premium_plus_membership.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_ebd9a6004e663bc2f9f4647f6f77e7960eb56201.yml
* adds support for premium plus
* moves premiumplus charge activity to own endpoint template
* removes comments, and info about plans from plan purchase template
* minor refactoring of charges controller
> adds support for premium plus (#1044)

- app/controllers/charges_controller.rb
- app/views/charges/create.html.erb
- app/views/charges/premium.html.erb
- app/views/charges/premiumplus.html.erb
- features/charge_activity.feature
- features/step_definitions/charge_steps.rb
- features/support/fixtures/cassettes/Charge_Users_Money/Sign_up_for_premium_plus_membership.yml
- features/support/fixtures/req_cache/get_csi.gstatic.com_ebd9a6004e663bc2f9f4647f6f77e7960eb56201.yml
* adds support for premium plus
* moves premiumplus charge activity to own endpoint template
* removes comments, and info about plans from plan purchase template
* minor refactoring of charges controller
> adds support for premium plus (#1044) (#1111)

- app/controllers/static_pages_controller.rb
- spec/routing/static_pages_routing_spec.rb
@diraulo a possible hotfix to the email marketing link failure.
> Hotfix for email link failure

- app/models/event.rb
- features/events/show_event.feature
- spec/models/event_spec.rb
> adjusts event show page to include hangout button during event duration if not actually already live

- app/views/events/index.html.erb
- features/events/list_events.feature
- features/step_definitions/event_steps.rb
> Implement correct date on index view Associated cuke

- app/controllers/events_controller.rb
- app/views/events/_form.html.erb
- features/events/edit_future_event.feature
- features/step_definitions/event_steps.rb
We weren't too happy about this fix, but couldn't think of any approach that seemed obviously better.
fixes #934
> 934 event edit state

- features/scrums.feature
> adds intermittent fail tag to scrums.feature:22

- app/assets/stylesheets/global/docs.scss
> allow overflow from doc-preview section

- app/assets/stylesheets/global/projects.scss
- app/assets/stylesheets/global/users.scss
- app/views/users/_user_list.html.erb
> Fix some overflow issues for users displayed in user list

- app/assets/stylesheets/global/projects.scss
- app/assets/stylesheets/global/users.scss
- app/views/users/_user_list.html.erb
> Fix layout issues associated with more text for users in list view

- app/models/user.rb
- app/services/karma_calculator.rb
- app/views/users/profile/_detail.html.erb
- features/step_definitions/commit_count_steps.rb
- features/users/activities.feature
- spec/models/commit_count_spec.rb
- spec/models/user_spec.rb
- spec/services/karma_calculator_spec.rb
> 1228 explain karma

- app/assets/stylesheets/layout/landing-page.scss
- app/views/visitors/index.html.erb
> improves layout landing page mobile

- app.json
- package.json
Pulling this in to clear blocking issue.
> Fix heroku deploy by adding bower to deps

- app/views/layouts/_footer.html.erb
- app/views/layouts/_sponsors.html.erb
- features/pages.feature
> updates sponsor links/alts

- app/models/karma.rb
- app/models/user.rb
- app/presenters/event_instance_presenter.rb
- app/services/karma_calculator.rb
- app/views/users/profile/_detail.html.erb
- db/migrate/20160921152810_create_karmas.rb
- db/schema.rb
- features/devops/github_commits.feature
- features/devops/karma_calculator.feature
- features/step_definitions/devops_steps.rb
- features/step_definitions/hangout_steps.rb
- features/step_definitions/karma_calculator_steps.rb
- features/support/hooks.rb
- features/users/activities.feature
- lib/tasks/scheduler.rake
- spec/factories/event_instances.rb
- spec/factories/karmas.rb
- spec/factories/users.rb
- spec/models/karma_spec.rb
- spec/models/user_spec.rb
- spec/presenters/event_instance_presenter_spec.rb
- spec/services/karma_calculator_spec.rb
- spec/views/event_instances/index.html.erb_spec.rb
> 1290 karma credit for participating in hangouts

- app/controllers/users_controller.rb
- app/models/user.rb
- app/services/karma_calculator.rb
- app/views/users/_user_list.html.erb
- db/migrate/20160928132707_remove_karma_from_user_table.rb
- db/migrate/20160928134250_rename_karma_karma_to_total.rb
- db/schema.rb
- spec/factories/karmas.rb
- spec/models/user_spec.rb
- spec/services/karma_calculator_spec.rb
> Moves Karma points from user table to karma table

- app/models/user.rb
- features/support/fixtures/cassettes/Manage_Document/A_user_can_insert_an_image.yml
- spec/models/user_spec.rb
> ensures user object cannot have nil karma

- app/views/layouts/_footer.html.erb
- app/views/layouts/_sponsors.html.erb
- spec/views/layouts/layouts_footer.html.erb_spec.rb
- spec/views/layouts/sponsors.html.erb_spec.rb
fixes #1329
Direct English-language users to the correct Craft Academy page
> Correct Craft Academy link

- app/models/event.rb
- features/hangouts/hangout.feature
- spec/models/event_spec.rb
> fix for failing to update hangout link manually

- Gemfile
- Gemfile.lock
> adds railroady

- .gitignore
- app/controllers/event_instances_controller.rb
- app/models/event.rb
- app/models/event_instance.rb
- app/views/events/show.html.erb
- db/migrate/20161028144621_add_url_set_directly_column_to_event_instance.rb
- db/schema.rb
- features/hangouts/edit_hangout_url.feature
- features/hangouts/hangout.feature
- features/step_definitions/hangout_steps.rb
- spec/controllers/event_instances_controller_spec.rb
- spec/models/event_instance_spec.rb
> make manually updated hangouts stay live for the duration

- app/views/events/show.html.erb
> some more elements needed by agile bot

- app/views/events/index.html.erb
> only check for event liveness on day of event

- app/models/project.rb
- config/initializers/friendly_id.rb
- db/migrate/20161103011445_create_friendly_id_slugs.rb
- db/schema.rb
- spec/models/project_spec.rb
Fixes the bug described at https://github.com/AgileVentures/WebsiteOne/issues/828 
fixes #828
> Regenerate friendly ids on projects when title is updated

- features/basic_layout.feature
- spec/views/layouts/layouts_footer.html.erb_spec.rb
> Convert footer spec to cuke

- app/views/layouts/_navbar.html.erb
- features/basic_layout.feature
- features/step_definitions/basic_steps.rb
- features/users/profile.feature
> Add create event link to navbar

- app/presenters/event_instance_presenter.rb
- config/locales/en.yml
- features/projects/project_videos.feature
- features/step_definitions/youtube_steps.rb
- features/support/fixtures/cassettes/See_project_related_videos/Selecting_videos_from_the_list.yml
- spec/presenters/event_instance_presenter_spec.rb
> returns more informative error message if video is missing

- app/views/projects/_listing.html.erb
- features/projects/list_projects.feature
> Remove code climate for now

- app/controllers/charges_controller.rb
- app/views/projects/_listing.html.erb
- features/premium/upgrade_membership.feature
- features/step_definitions/charge_steps.rb
> add sad path for membership upgrade and tighten up upgrade tests

- app/views/projects/_activity.html.erb
- app/views/projects/_connections.html.erb
- features/projects/project_pivotal_stories.feature
- spec/views/projects/show.html.erb_spec.rb
Change project view text from 'Pivotal Tracker' to 'Issue Tracker'
fixes #1410 
Ran cucumber, jasmine, and rspec tests
I visually checked the screens.
> 1410 fix tracker text

- Gemfile
- Gemfile.lock
This is the result file for the execution of the gem **Eefgilm**.
Related to: #1369 .
Fixes #1404 .
> Gemfile cleanup

- app/services/upgrade_user_to_premium.rb
- features/premium/upgrade_membership.feature
- features/step_definitions/charge_steps.rb
- spec/services/upgrade_user_to_premium_service_spec.rb
> feature to ensure upgraded to premium user has title added to title list

- app/controllers/subscriptions_controller.rb
- app/mailers/mailer.rb
- app/views/mailer/send_sponsor_premium_payment_complete.html.erb
- config/settings/production.yml
- features/hire_me_modal.feature
- features/premium/sponsor_other_member.feature
- features/premium/subscribe_self_to_premium.feature
- features/step_definitions/email_steps.rb
> support for sponsored AVP emails and more generic smtp settings

- app/services/twitter_service.rb
- features/step_definitions/youtube_steps.rb
- spec/services/twitter_service_spec.rb
> Change logic to depend on actual_start_time

- config/routes.rb
- spec/controllers/subscriptions_controller_spec.rb
> Fix routing to disallow GET on subscriptions/upgrade

- app/views/subscriptions/new.html.erb
- lib/tasks/create_plans.rake
> adds other plans into rake task and minor fix to ensure all plans default to GBP

- app/controllers/subscriptions_controller.rb
- app/views/subscriptions/upgrade.html.erb
- app/views/users/profile/_premium_mob_upgrade.html.erb
- app/views/users/profile/_summary.html.erb
- features/premium/upgrade_membership.feature
> make upgrade option mob only in the first instance

- app/assets/stylesheets/global/custom.scss
- app/assets/stylesheets/layout/buttons.scss
- app/views/layouts/_round_banners.html.erb
- features/step_definitions/user_steps.rb
- features/users/sign_in.feature
> 1536 hide call to action when signed in

- app/views/subscriptions/create.html.erb
> throws adwords script in premium created view

- app/views/layouts/_escalating_call_to_action.html.erb
- app/views/layouts/_round_banners.html.erb
- features/articles.feature
- features/escalating_call_to_action.feature
- features/step_definitions/basic_steps.rb
- features/step_definitions/user_steps.rb
- features/users/sign_up.feature
> Escalating call to action

- CONTRIBUTING.md
- docs/README.md
- docs/development_environment_set_up.md
- docs/project_setup.md
This fixes issue #1547 
I made it clear that the CONTRIBUTING.md document is about process and workflow.  I put a reference to getting the development environment set up (project_set_up.md) right up top.  
There also wasn't any connection between setting up the development environment and the document actually named 'development_environment_set_up.md' (which is about some specific potential trouble areas). Those are now linked (references are made where appropriate in the documents).  'docs/README.md' was re-ordered to follow the sequence that a developer would typically follow and a link to CONTRIBUTING.md was added.
Specific changes to  **Setting up a Development environment (project_set_up.md):**
- added an intro so the scope and focus of the document is clear
- misc. grammar fixes
- …
> clarify setting up dev environment vs. Contributing (workflow)

- app/controllers/authentications_controller.rb
- app/controllers/registrations_controller.rb
- app/views/layouts/_adwords_signup_conversion.html.erb
- app/views/visitors/index.html.erb
- features/step_definitions/user_steps.rb
- features/users/sign_up.feature
> spikes a flash setting to add the adwords conversion tracking after sign up

- app/models/event.rb
- app/views/layouts/_event_link.html.erb
- features/events/next_scrum.feature
- features/hangouts/hangout.feature
- features/step_definitions/basic_steps.rb
- features/support/capybara.rb
- spec/spec_helper.rb
Work in progress for #1517 
Added 2 scenarios that pass with the hotfix and fail without it.  The third on line 97 should be failing without the hotfix, but is passing.  Help would be appreciated.
> WIP #1517 next scrum

- app/views/users/profile/_summary.html.erb
> adjust mail to link in user summary

- app/controllers/authentications_controller.rb
- app/views/layouts/_flash.html.erb
- features/users/sign_up.feature
> adjust how signup flash is displayed

- app/views/subscriptions/new.html.erb
- features/step_definitions/premium_steps.rb
> Adjusts stripe button subscription wording

- app/views/layouts/_escalating_call_to_action.html.erb
- db/schema.rb
- features/escalating_call_to_action.feature
> Adjust text on call to action

- app/views/users/profile/_premium_mob_upgrade.html.erb
- app/views/users/profile/_premium_upgrade.html.erb
- config/locales/en.yml
- features/premium/upgrade_membership.feature
- features/step_definitions/premium_steps.rb
> Tooltips to explain Premium upgrade buttons

- app/controllers/registrations_controller.rb
- features/step_definitions/basic_steps.rb
- features/users/sign_up.feature
- spec/controllers/registrations_controller_spec.rb
> get users onto getting started after sign up

- app/views/layouts/_flash.html.erb
- features/projects/edit_project.feature
- features/step_definitions/basic_steps.rb
- features/users/activities.feature
- features/users/link_github.feature
> fix for missing flash background with associated test

- app/views/layouts/_footer.html.erb
> Add charity id to footer

- app/assets/stylesheets/global/social.scss
- app/helpers/application_helper.rb
- features/users/omniauth.feature
- features/users/sign_up.feature
- spec/requests/authentications_spec.rb
- spec/views/devise/sessions/new.html.erb_spec.rb
> Adjusting G+ buttons

- app/views/layouts/_footer.html.erb
- features/basic_layout.feature
fixes #1575 
Should also add to editable about-us page, as suggested.
> Add blog link to footer

- app/controllers/static_pages_controller.rb
- config/routes.rb
> letsencrypt endpoint

- app/helpers/layout_helper.rb
- app/views/layouts/_escalating_call_to_action.html.erb
- features/escalating_call_to_action.feature
- features/events/event_countdown.feature
- features/events/next_scrum_for_new_user.feature
- features/events/show_event.feature
- spec/views/visitors/index.html.erb_spec.rb
> couple of minor text updates

- app/assets/stylesheets/global/custom.scss
- app/assets/stylesheets/global/page.scss
- config/environments/development.rb
> increase base font size to 24

- package.json
> Lock down moment-timezone exactly

- app/models/event.rb
> tries a quick fix for #1635

- app/services/karma_calculator.rb
- features/step_definitions/user_steps.rb
- features/support/fixtures/cassettes/Show_Events/I_add_an_event_to_my_Google_Calendar.yml
- lib/tasks/scheduler.rake
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/services/karma_calculator_spec.rb
- spec/views/event_instances/index.html.erb_spec.rb
> Fix for nonexistant karma record, with pre-failing test

- app/assets/stylesheets/global/page.scss
> adjust static page font and line height as agreed by marketing

- app/jobs/github_commits_job.rb
- app/jobs/github_last_updates_job.rb
- app/services/error_logging_service.rb
- app/views/events/show.html.erb
- features/hangouts/edit_hangout_url.feature
- features/step_definitions/hangout_steps.rb
> 1669 ping project channels on manual update

- docs/c9/install_notes.md
Making the following changes:
Credits goes to Alex (https://agileventures.slack.com/team/alexander_kh) for suggesting these fixes.
> Improve c9 installation notes

- app/models/event.rb
- app/models/event_instance.rb
- spec/models/event_instance_spec.rb
Fixes #1686 
I have made the change so as to display Join Now after hangout link is edited.
> display "join now" only after hangout link is updated

- features/step_definitions/youtube_steps.rb
> Test for youtube links not working

- app/assets/stylesheets/global/projects.scss
- app/views/projects/_listing.html.erb
- app/views/projects/show.html.erb
> adjusts project main image sizes in listing and project page

- app/views/devise/registrations/new.html.erb
> add link to privacy statement fixes

- Gemfile
- Gemfile.lock
- app/controllers/event_instances_controller.rb
- app/models/event_instance.rb
- app/views/events/show.html.erb
- features/hangouts/edit_youtube_url.feature
- features/step_definitions/hangout_steps.rb
- spec/controllers/event_instances_controller_spec.rb
- spec/models/event_instance_spec.rb
> manual update of youtube link

- features/hangouts/edit_youtube_url.feature
> disable this test until we can figure out the issue better

- app/models/event.rb
> fix jitsy URLs

- app/models/project.rb
- app/views/events/show.html.erb
- app/views/projects/show.html.erb
- features/jitsi_meet/start_jitsi_button.feature
- features/step_definitions/jitsi_steps.rb
- spec/models/event_spec.rb
- spec/models/project_spec.rb
Adds test for https://github.com/AgileVentures/WebsiteOne/issues/1726
> test for start jitsi button on event and project page

- app/views/mailer/send_welcome_message.html.erb
- spec/mailers/mailer_spec.rb
> update welcome message

- app/controllers/registrations_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- features/step_definitions/user_steps.rb
- features/users/sign_up.feature
- lib/tasks/fix_karma.rake
> fix nill karma users

- app/models/event.rb
> experiment with only working out schedule for upcoming events

- app/controllers/event_instances_controller.rb
- features/hangouts/hangout.feature
> reduce initial number of hangouts displayed on page

- app/assets/stylesheets/global/hangouts.scss
- app/views/event_instances/_index_basic_info.html.erb
> zero margins over-ruling existing -15px margins looks good

- app/controllers/event_instances_controller.rb
> [WIP] Fix 'regex_dos' issue in event_instances_controller.rb; fixes #1795

- app/views/subscriptions/create.html.erb
- features/premium/subscribe_self_to_premium.feature
> avoid hard coding number of trial days

- app/views/static_pages/premium.html.erb
fixes #1715 
note that this view is not currently rendered - it's just a save of the latest changes I made to the staging server https://staging.agileventures.org/premium
maybe we want these pages to be in git rather than the database in the long run - we'll see.  Either way I wanted a copy in version control and something that I could edit outside mercury ...
> trying to improve premium page text

- lib/tasks/vcr_billy_caches.rake
> adds cache clearing task

- app/assets/javascripts/projects.js
- features/projects/create_projects.feature
- features/projects/edit_project.feature
- features/step_definitions/projects_steps.rb
> refactors javascript and ensures that github url fields are numbered correctly on initial load

- app/views/static_pages/premium_mob.html.erb
fixes #1713
Note, to review this in user friendly form go to https://staging.agileventures.org/premium_mob
> Puts new mob page in version control (backup only)

- app/views/static_pages/premium_f2f.html.erb
- app/views/static_pages/premium_mob.html.erb
> adjusts Premium F2F page (WIP)

- app/services/slack_service.rb
- spec/services/slack_service_spec.rb
* update hyperlink formatting for slack messages fixes #1880
* ensures videos for scrums go to project channels fixes #1881
> improvements to slack messages (hyperlinks and scrum videos to project channels)

- app/assets/javascripts/google-analytics.js
Add's Google Analytics User ID tracking code
Add's Google Analytics User ID tracking code so Marking can get a better understanding of a single user who visits the website.
Help Marketing understand a user that visits the website and their journey on the site
It has not been tested, we will only be able to check once in production to see if analytics is tracking the user.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests pass.
> 1760 adds tracking for userID

- app/controllers/static_pages_controller.rb
- config/routes.rb
related to #1826 but not actually a fix ...
> adding token for load testing

- app/controllers/static_pages_controller.rb
- config/routes.rb
related to #1826 but does not fix
> make loaderio token dynamic

- app/models/event.rb
- features/hangouts/edit_hangout_url.feature
- features/step_definitions/hangout_steps.rb
> cuke test and fix for pinging youtube url from previous scrum

- app/services/slack_service.rb
- spec/services/slack_service_spec.rb
> adjust messaging format

- app/controllers/application_controller.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
> feature flag to toggle preloading of next scrum

- app/views/static_pages/show.html.erb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
> add feature flag for editing static pages

- app/models/event.rb
- features/events/list_single_events.feature
> ensure one off events appear in the list of future events

- app/assets/javascripts/google-analytics.js
> comment out code that is breaking fixes #1968 comment out code causing breakage

- app/views/visitors/index.html.erb
> adjust text on landing page

- app/controllers/subscriptions_controller.rb
- app/models/subscription.rb
- app/services/add_subscription_to_user_for_plan.rb
- db/migrate/20171118201937_add_sponsor_column_to_subscription.rb
- db/schema.rb
- features/premium/sponsor_other_member.feature
- features/premium/subscribe_self_to_premium.feature
- features/step_definitions/sponsors_steps.rb
- spec/services/add_subscription_to_user_for_plan_spec.rb
- Add sponsor_id column to subscriptions table
- Set sponsor to current user in the subscriptions controller
fixes #1960
> 1960 Add sponsor relationship

- db/schema.rb
- spec/lib/custom_errors_spec.rb
- spec/models/event_spec.rb
> clearing up specs

- app/views/events/index.html.erb
- features/events/list_repeating_events.feature
- features/step_definitions/event_steps.rb
> add auto_link to list view of event descriptions to avoid raw html and refactor cuke

- spec/services/slack_service_spec.rb
fixes #1888
started with some mock_models - makes it feel like we really need some high level acceptance tests for all this ...
> [WIP] refactoring slack service 

- app/controllers/event_instances_controller.rb
> just try adjusting the point that firefox quantum fails on

- app/models/subscription.rb
- app/views/api/subscriptions/index.json.jbuilder
- spec/requests/api_subscriptions_spec.rb
> include sponsor email in api

- app/views/layouts/_footer.html.erb
- features/basic_layout.feature
The link text was corrected to reflect the correct sponsor name.
The following view:
/app/views/layouts/_footer.html.erb:36
was updated with the correct link text.
The footer on Website one displays an incorrect Sponsor name.
An existing Cucumber scenario was amended to test for the corrected test
/features/basic_layout.feature:42
> 2016 - change 'Standuply' sponser text in footer to 'Standup Bot'

- app/controllers/application_controller.rb
- app/controllers/subscriptions_controller.rb
- features/premium/charge_activity.feature
- features/premium/sponsor_other_member.feature
- features/premium/subscribe_self_to_nonprofit_basic.feature
- features/premium/subscribe_self_to_premium.feature
- features/premium/subscribe_self_to_premium_mob.feature
- features/step_definitions/basic_steps.rb
- features/support/helpers.rb
> adding a logged in requirement for premium subscriptions

- app/controllers/visitors_controller.rb
- app/views/layouts/_event_link.html.erb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
> allows us to turn off the homepage next scrum, but leave it on other pages

- app/assets/stylesheets/layout/buttons.scss
> removes top margin on HOA button

- app/views/users/index.html.erb
> fix open div on index view

- .codeclimate.yml
> Exclude public path from codeclimate analysis.

- app/services/slack_service.rb
> add rundfunk slack channel

- Gemfile.lock
Issue related: https://github.com/AgileVentures/WebsiteOne/issues/2255
> Moving to a safe 'loofah' version with no security issues.

- app/models/payment_source.rb
- spec/models/payment_source_spec.rb
This pr adds other types of payments sources 
fixes #2268
Its been tested by writing tests on the corresponding rspec file
> Add other types of payment sources solves#2268

- spec/helpers/documents_helper_spec.rb
This fixes https://github.com/AgileVentures/WebsiteOne/issues/2330
> Fix 'documents helper spec.'

- db/schema.rb
Fix schema.
@tansaku  this PR reverts the changes I generated when migrating and using the dump from production:
If you want to check the file on the above image you can go [here](https://github.com/AgileVentures/WebsiteOne/pull/2302/files#diff-1acd2e7e27a227829d5d14a91c863bb6)
> Fix schema.

- lib/custom_errors.rb
> Fix undefined variable env error

- app/assets/stylesheets/global/static_pages.scss
improves the line spacing
fixes #2297
> change css for static pages line height 

- spec/models/project_spec.rb
> Fix failing test for model method send notification to project creator

- features/pages.feature
- features/projects/edit_project.feature
These features were hanging around but the functionality no longer exists.
> Remove Mercury features affecting CI

- features/devops/github_commits.feature
VCR got updated when working github related stories.
> VCR got updated when working github related stories.

- .simplecov
- config/cucumber.yml
- lib/tasks/ci.rake
> Activate second try.

- app/models/project.rb
- app/views/projects/_connections.html.erb
- features/projects/connections.feature
- features/projects/create_projects.feature
- features/projects/edit_project.feature
- features/projects/show_project.feature
- features/step_definitions/projects_steps.rb
Refactor connections feature spec to use scenario outline
Fixes #2503 
To dry out code
> 2503 refactor connections feature

- Dockerfile
- docker-compose.yml
- docker/setup.sh
> Better dev flow with docker

- app/controllers/subscriptions_controller.rb
- app/controllers/users_controller.rb
- app/views/users/profile/_set_level.html.erb
- app/views/users/profile/_summary.html.erb
- config/database.yml
- config/environments/development.rb
- config/settings/development.yml
- config/settings/test.yml
- db/schema.rb
- features/premium/downgrade_membership.feature
- features/step_definitions/user_steps.rb
- features/support/helpers.rb
> [WIP] rough draft of manipulating premium sponsor levels to

- app/views/av_dashboard_tokens/create.html.erb
simple fix for the javascript "forwarding" step that isn't working right now because of the necessary www on the front.
@tansaku please pull in
> Fix forwarding domain for dashboard

- app/services/karma_calculator.rb
- db/migrate/20180810180605_add_karma_breakdown_elements_to_karma_table.rb
- db/schema.rb
- lib/tasks/scheduler.rake
- spec/services/karma_calculator_spec.rb
fixes #1295
Bit of renaming, memoization, few improvements which i think we could make here.
I wasn't clear with info i got from the above ticket, but i did this much with the understanding i had.
No tests added yet because i wanted to be sure that i haven't done something unnecessary.
@tansaku  @mattwr18  need your reviews :)
> add other karma breakdown elements to karma table

- docs/how_to_setup_av_dashboard_token_endpoint.md
> Add basic docs for setting up av dashboard token endpoint and giving access

- app/views/users/profile/_set_level.html.erb
> quick defence against absence of existing subscription

- config/settings/production.yml
> add www prefix

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
> Move to headless chromedriver

- docker/README.md
docker/README.md is missing info about the env variables for setting up the database. Without it docker-compose throws an error
Updated the readme, also added some more info about running  the tests inside a container 
I had an error when setting up docker and I found that there is a github issue for this problem. So I decided to update the README file
Tested on my machine, the build passes
> Updated docker setup README file fixes #2617

- app/views/events/show.html.erb
- features/events/start_event.feature
fixes #2664
With enclosed feature
> Test for bug and fix it

- app/helpers/event_helper.rb
- app/services/slack_service.rb
- features/events/private_events.feature
- features/step_definitions/user_steps.rb
> ensure only Premium Mob members and above can see mob event join buttons

- app/views/layouts/_round_banners.html.erb
Make entire hovered home page circles clickable
Fixes #1615 
Make entire hovered home page circles clickable
Fixes #1615 
Changes were tasted locally
> Make entire hovered home page circles clickable

- .rubocop.yml
> Update rubocop.yml to latest release

- docs/c9/install_notes.md
Updated ruby version.
Run bundle install without production gems. No need to install
production gems in the development environment.
Wrapped inline code with backtick.
Added fix for db encoding issue.
> Update documentation for c9 install

- app/views/events/show.html.erb
- features/events/private_events.feature
- features/step_definitions/basic_steps.rb
> Add link to upgrade on premium mob events, test

- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
Currently to update the Gemfile we need to rebuild the whole docker image
Implement separate image for gems using this [tutorial](https://medium.com/@jfroom/docker-compose-3-bundler-caching-in-dev-9ca1e49ac441)
> [WIP][docker]gems version checking and updating

- app/controllers/events_controller.rb
- app/models/project.rb
- app/views/events/_form.html.erb
- app/views/events/index.html.erb
- features/events/create_events.feature
- features/events/events_by_project.feature
- features/step_definitions/event_steps.rb
- spec/requests/events_spec.rb
fixes #2665 
- Filter by active projects
Filter to display only active projects on projects dropdown
fixes #1812
> Events page Projects dropdown

- Gemfile
- Gemfile.lock
- app/controllers/calendar_controller.rb
- app/views/events/index.html.erb
- config/routes.rb
- features/events/upcoming_events.feature
- features/step_definitions/basic_steps.rb
- spec/controllers/calendar_controller_spec.rb
fixes #2769
Allow to use events in external calendar app
Visiting site 5 times a day to check whats planned for today is a bit boring
> add possibility to download events as calendar file

- db/seeds.rb
In development there's no easy way to test premium user features
Also updated events to have current date - now we can see them in the calendar.
fixes #2718
Updated seed file to generate 4 premium users all with password: premium123
and emails: 
- premium@premi.um
- premiummob@premi.um
- premiumf2f@premi.um
- premiumplus@premi.um
This might need adding to the docs
I've run the file a couple of times when testing docker updates
> seeding premium users and events with current date

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
fixes #2793 
PR template now looks like this
This doesn't require automated testing by us since part of github, but all devs should look over the new templates to agree on the new format.
Thanks so much to @diraulo for adding the originals, and apologies it has taken us (me!) so long to actually work on adjusting them to our particular project workflow :-(
> rough changes to PR template

- app/jobs/github_readme_files_job.rb
Refactor GitHubReadmeFilesJob using extract method, replace temp with query, etc
fixes #2681
> 2681 refactoring relative links

- app/views/events/index.html.erb
- features/events/events_by_project.feature
- features/step_definitions/event_steps.rb
> Reset projects filter on events page after hit back

- features/step_definitions/user_steps.rb
- features/users/sign_in.feature
- Remove ci-ignore tag
fixes #2703 
- Update step definitions for finding link
> Resolve Intermitent Failing Test

- app/jobs/github_commits_job.rb
- app/jobs/github_languages_job.rb
- app/jobs/github_last_updates_job.rb
- app/models/project.rb
- spec/models/project_spec.rb
switch the github username and reponame to appear correctly
fixes #2576
> switch GitHub user name with repo name

- app/views/static_pages/internal_error.html.erb
- features/customerrors.feature
> 2883 improve 500 error page

- app/models/project.rb
- app/models/slack_channel.rb
- db/migrate/20181220155404_create_slack_channel.rb
- db/migrate/20181220160421_create_join_table_project_slack_channel.rb
In this PR I want to refactor the notifications code before add the new notifications for slack asked in #2802
> Refactor Slack Notifications

- app/jobs/github_languages_job.rb
> #2725 Import languages from multiple repos.

- app/jobs/github_languages_job.rb
- features/devops/github_languages.feature
- features/step_definitions/projects_steps.rb
Pulls in languages from all a project's repos
fixes #2725 
more than one github_url add to a project's source_repositories, check that languages from the 2nd or 3rd repo appear in a project's languages
> Check that languages from multiple repos are imported

- Dockerfile
> Updates ruby version to 2.5.1 in Docker file

- app/jobs/github_languages_job.rb
- features/support/fixtures/cassettes/Update_github_languages_field_of_all_projects/Update_language_field_of_all_projects_with_valid_github_url.yml
- on unique constraint error, retry, apparently due to flakiness of `find_or_create_by` https://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by
- not sure what the diff between this fixture is, it can be removed if it's not needed to be updated
fixes #3197
> Update github languages job, fixture

- app/models/event.rb
- features/step_definitions/event_steps.rb
- spec/controllers/calendar_controller_spec.rb
- spec/factories/events.rb
- spec/migrations/event_time_refactor_spec.rb
- spec/models/event_spec.rb
This PR fixes the issue below by validating repeat_ends field in Event model
fixes [#2926](https://github.com/AgileVentures/WebsiteOne/issues/2926)
Fix failing test by adding repeat_ends field to factories
> Add validation for repeat_ends in event model

- app/controllers/paypal_agreement_controller.rb
- app/services/paypal_service.rb
- lib/tasks/create_plans.rake
- spec/requests/paypal_agreement_spec.rb
- Co-authored-by: Mike Aono <aonomike@gmail.com>
- Co-authored-by: Cire DIA <ciremoussadia@gmail.com>
fixes #3220
> Set up rake task to create paypal plans and update db

- app/assets/stylesheets/global/custom.scss
- app/views/projects/_form.html.erb
- features/projects/edit_project.feature
Added message next to the `Image url` title to inform users how to edit images. WIP b/c there are other hints discussed in the original that can be implemented if the existing page is not clear.
fixes #2941
> Add guide to Edit Project Feature

- app/controllers/subscriptions_controller.rb
- app/views/subscriptions/create.html.erb
- app/views/subscriptions/new.html.erb
> Refactoring subscription controller

- app/views/users/profile/_summary.html.erb
- Moved the `Update Card Button` to below the `Edit Status` button
- Added spacing above member status to better differentiate the buttons
Any feedback (especially design) would be appreciated.
fixes #3008
> [WIP] Improve UX for User Profile Card Details

- db/seeds.rb
> update Faker deprecated methods

- features/step_definitions/premium_steps.rb
Fixed broken tests
Fixes #3549
> Replace fixed cc-exp with dynamic date

- app/views/public_activity/article/_create.html.erb
- app/views/public_activity/article/_update.html.erb
- app/views/public_activity/document/_create.html.erb
- app/views/public_activity/document/_update.html.erb
- app/views/public_activity/project/_create.html.erb
- app/views/public_activity/project/_update.html.erb
> fixes try method on WET activity views

- app/views/mailer/send_welcome_message.html.erb
- features/jitsi_meet/start_jitsi_button.feature
- spec/mailers/mailer_spec.rb
* updates welcome mailer content
* removes mention about canceled Premium Mob Membership
fixes #
> Mailer content

- app/controllers/dashboard_controller.rb
- app/views/dashboard/index.html.erb
adds sanitizer to activities collection to avoid 500 errors
fixes #
> fixes map display

- Gemfile.lock
> pushes develop to staging

- app/controllers/application_controller.rb
- app/controllers/scrums_controller.rb
- app/helpers/scrums_helper.rb
- app/views/scrums/index.html.erb
- app/views/visitors/index.html.erb
- features/events/past_events_page.feature
- features/past_events.feature
- features/step_definitions/scrums_steps.rb
- spec/controllers/scrums_controller_spec.rb
* changes method to pull up events on Past Events controller
* gets rid of vanity 
fixes #
> Content updates and refactorings
